// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serivce.proto

package com.guan.sso.server.grpc.server;

public interface LogoutReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.LogoutReply)
    com.google.protobuf.MessageOrBuilder {
}
