// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serivce.proto

package com.guan.sso.server.grpc.server;

public interface TokenReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TokenReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   */
  long getUid();
}
