// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_data.proto

package com.guan.sso.server.grpc.stub;

public interface AuthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string acn = 1;</code>
   */
  String getAcn();
  /**
   * <code>string acn = 1;</code>
   */
  com.google.protobuf.ByteString
      getAcnBytes();

  /**
   * <code>string pwd = 2;</code>
   */
  String getPwd();
  /**
   * <code>string pwd = 2;</code>
   */
  com.google.protobuf.ByteString
      getPwdBytes();
}
