// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_data.proto

package com.guan.sso.server.grpc.stub.auth;

public interface AuthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string acc = 1;</code>
   */
  String getAcc();
  /**
   * <code>string acc = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccBytes();

  /**
   * <code>string pwd = 2;</code>
   */
  String getPwd();
  /**
   * <code>string pwd = 2;</code>
   */
  com.google.protobuf.ByteString
      getPwdBytes();
}
