// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_data.proto

package com.guan.sso.server.grpc.stub.auth;

public interface AuthReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
